project:
  type: website

website:
  title: "Наш проект"
  navbar:
    left:
      - href: index.qmd
        text: Домой
      - about.qmd
    logo: medium

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    title-logo: logo
    respect-user-color-scheme: true



